In [1]:
print("Hello numpy!")

Hello numpy!


PYTHON REVIEW o/

In [2]:
#Python Review!
# Function
def times2(var):
    return var*2 

In [3]:
times2(5)

10

In [4]:
def square(num):
    '''
    THIS IS DOCSTRING,
    CAN GO MULTIPLE LINES
    THIS FUNCTION SQUARES A NUMBER.
    '''
    return num**2

In [5]:
square(5)

25

MAP in PYTHON

In [6]:
seq=[1,2,3,4,5]

In [7]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

LAMBDA in PYTHON

In [8]:
l=lambda var:var*2 

In [9]:
l(5)

10

FILTER in PYTHON

In [10]:
list(filter(lambda num:num%2==0, seq))

[2, 4]

STRING in PYTHON

In [11]:
s='hello my name is j3!'

In [12]:
s.upper()

'HELLO MY NAME IS J3!'

In [13]:
s.lower()

'hello my name is j3!'

In [14]:
s.capitalize()

'Hello my name is j3!'

In [15]:
tweet='Go Sports!#Sport'

In [16]:
tweet.split('#')[0]

'Go Sports!'

In [17]:
tweet.split('#')[1]

'Sport'

In [18]:
# Number of times the word 'dog' occurs in a string
def countDog(phrase):
    count=0
    for word in phrase.lower().split():
        if word == 'dog':
            count+=1
    return count


In [19]:
countDog('This dog runs faster than the other dog')

2

In [20]:
seq=['soup', 'dog','salad','cat','gread']

In [21]:
list(filter(lambda var:var[0]=='s', seq))

['soup', 'salad']

DICTIONARY in PYTHON

In [22]:
d={'key1':1, 'key2':2}

In [23]:
d.keys()

dict_keys(['key1', 'key2'])

In [24]:
d.items()

dict_items([('key1', 1), ('key2', 2)])

In [25]:
d.values()

dict_values([1, 2])

LIST in PYTHON

In [26]:
lst=[1,2,3]

In [27]:
item=lst.pop()

In [28]:
lst

[1, 2]

In [29]:
item

3

In [30]:
lst.append(3)

In [31]:
lst

[1, 2, 3]

TUPLE UNPACKING in PYTHON 

Python tuples are immutable means that they can not be modified in the whole program.

Packing and Unpacking a Tuple: In Python, there is a very powerful tuple assignment feature that assigns the right-hand side of values into the left-hand side. In another way, it is called the unpacking of a tuple of values into a variable. In packing, we put values into a new tuple while in unpacking we extract those values into a single variable.

In [32]:
x=[(1,2),(3,4),(5,6)]

In [33]:
x[0][0]

1

In [34]:
type(x)

list

In [35]:
for item in x:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [36]:
for (a,b) in x:
    print(a+1, b+1)

2 3
4 5
6 7


In [37]:
for a,b in x:
    print(a)

1
3
5


In [38]:
for a, b in x:
    print(b)

2
4
6


NUMPY

Numpy is The fundamental Package for Scientific Computing with Python!

The reason it is so important for Data Science with Python is that a lot of all the libraries in the Python Ecosystem rely on NUMPY as one of their main building blocks (Jose Portilla — Python For Data Science course).

https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/

NUMPY ARRAYS . vectors (1-dimensional)
             . matrices (1 or more dimensionals)



In [39]:
# Vectors
my_list=[1,2,3]
import numpy as np 
vec=np.array(my_list)
vec

array([1, 2, 3])

In [40]:
# Matrices
# 2 brackets mean 2-dimensional
my_mat=[[1,2],[3,4],[5,6]]
import numpy as np 
mat=np.array(my_mat)
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

ARANGE in NUMPY


In [41]:
# From zero to all the way up but not including 10 (return a sequence)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# The third paramenter means STEP SIZE
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

ZEROES in NUMPY

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ONES in NUMPY

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

LINSPACE (SPACED EVENLY) in NUMPY 

In [47]:
# From zero to 5 returning 10 points evenly spaced!
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

PLEASE DON’T CONFUSE linspace WITH arange:

arange: will take in the third argument as the STEPS SIZE (you want)

linspace: will take in the third argument as the NUMBER OF POINTS(evenly separated)

IDENTITY in NUMPY

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

RANDOM in NUMPY

In [49]:
# RAND differs from ARANGE because RAND returns random numbers and ARANGE return a sequence of them
np.random.rand(5)

array([0.10528633, 0.70838302, 0.67936816, 0.17844214, 0.46440859])

In [50]:
#  n means Normal Distribution (return values around the Mean in gaussian distribution)
np.random.randn(2)

array([-1.68412494,  1.13015504])

In [51]:
# Without the third parameter, it will return one digit 
np.random.randint(1,100)

53

In [52]:
# The third parameter specifuy the digits you want to return
np.random.randint(1,100,10)

array([76, 76, 12, 22, 60, 59, 97, 90, 67, 97])

Difference between ARANGE and RANDINT:

ARANGE: returns sequence of digits

RANDINT: returns randonly selected digits

In [53]:
arr=np.arange(25)

In [54]:
# It is a sequence!
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
randarr=np.random.randint(0,50,10)

In [56]:
# it is a matrix...
randarr

array([10,  0,  3, 25, 23,  9, 46, 30,  8, 19])

RESHAPE in NUMPY

In [57]:
# ...that can be reshapped!
randarr.reshape(5,2)

array([[10,  0],
       [ 3, 25],
       [23,  9],
       [46, 30],
       [ 8, 19]])

In [58]:
randarr.max()

46

In [59]:
randarr.min()

0

ATTRIBUTES in NUMPY

(there are no Parentheses cuz this is attributes:)

In [60]:
randarr.shape

(10,)

In [61]:
randarr.dtype

dtype('int32')

In [62]:
from numpy.random import randint

In [63]:
# LINK https://medium.com/jungletronics/numpy-init-python-review-f5362abbaaf9
print("Thank you for reading this page! Please favorite it, IF YOU LIKE IT!")

Thank you for reading this page! Please favorite it, IF YOU LIKE IT!


# FUN LITTLE QUIZ
SOLUTION Nº 01

In [68]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


SOLUTION Nº 02

In [73]:
matrix_b=np.genfromtxt('matrix_b.txt', delimiter=',')
matrix_b

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.],
       [1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.],
       [1., 2., 3., 4., 5.]])

In [76]:
matrix_c=matrix_b[2:4,0:2]
print(matrix_c)

[[1. 2.]
 [6. 7.]]


In [80]:
matrix_d=matrix_b[[0,1,2,3],[1,2,3,4]]
print(matrix_d)

[2. 8. 4. 0.]


In [108]:
matrix_e=matrix_b[[2,4],2:5]
print(matrix_e)

[[3. 4. 5.]
 [3. 4. 5.]]
