### CREMER RULE

Cramer's rule is an explicit formula for the solution of a system of linear equations with as many equations as unknowns, valid whenever the system has a unique solution. It expresses the solution in terms of the determinants of the (square) coefficient matrix and of matrices obtained from it by replacing one column by the column vector of right-hand-sides of the equations. (from https://en.wikipedia.org/wiki/Cramer%27s_rule)

### EQUATIONS SYSTEMS  - PROBLEM


A production engineer from an electronics industry analyzes an industrial process in which he considers the assembly time (t), the number of employees (x) and the number of components (n) used in the final product, and reached this system of equations:

The engineer wants to reach an ideal condition for all goals to be achieved, with an estimated accuracy of 0.01 (one hundredth of each variable).

\
  \begin{cases}
      2t + 1x +    1n = 39   & \quad \text{ } t \text{ }\\
    0.3t + 2x + 0.25n = 13   & \quad \text{ } x \text{}\\
       t +  x +    2n = 45  & \quad \text{ } n \text{
       }
  \end{cases}
  
  A = \begin{bmatrix}
       2.0 & 1.0 & 1.0 \\
       0.3 & 2.0 & 0.25 \\
       1.0 & 1 & 2\\
     \end{bmatrix}
     
   B = \begin{bmatrix}
       \color{red}3\color{red}9 \\
       \color{red}1\color{red}3 \\
       \color{red}4\color{red}5\\
     \end{bmatrix}
  
  ####    HOW TO SOLVE THIS PROBLEM USING CREMER RULE.
  
A1 = \begin{bmatrix}
       {\color{red}3\color{red}9} & 1.0 & 1.0 \\
       \color{red}1\color{red}3 & 2.0 & 0.25 \\
       \color{red}4\color{red}5 & 1.0 & 2.0\\
     \end{bmatrix}
     
A2 = \begin{bmatrix}
       2.0 & \color{red}3\color{red}9 & 1.0 \\
     0.3 & \color{red}1\color{red}3 & 0.25 \\
       1.0 & \color{red}4\color{red}5  & 2.0\\
     \end{bmatrix}
     
A3 = \begin{bmatrix}
       2.0 & 1.0 & \color{red}3\color{red}9 \\
     0.3 & 2.0 & \color{red}1\color{red}3 \\
       1.0 & 1.0 & \color{red}4\color{red}5\\
     \end{bmatrix}
     
     
     
     
                                         TWO Conditions for CREMER RULE application:
 
\begin{array}{c|c}
   (1)& matrix&must& be& square \\ 
  \hline
  (2)& detA& must &be &different& of& zero
 \end{array}
  

In [1]:
# cremer rule
from numpy import matrix, linalg
import numpy as np

In [2]:
# creating the matrices
matrix_A = np.array([[2.0, 1.0, 1.0],[0.30, 2.0, 0.25],[1.0, 1.0, 2.0]])
print(matrix_A)

[[2.   1.   1.  ]
 [0.3  2.   0.25]
 [1.   1.   2.  ]]


In [3]:
matrix_B = np.array([[39.0],[13.0],[45.0]])
print(matrix_B)

[[39.]
 [13.]
 [45.]]


In [4]:
# calculating the determinant of th ematrix_A
det_A = linalg.det(matrix_A)

In [5]:
# Is IT POSSIBLE TO USE cremer rule?
if(det_A == 0):
    print('This equation CANNOT BE SOLVED by CREMER RULE:/')
else:
    print('det_A = ', det_A )

det_A =  5.45


In [6]:
# fetching matrix_B's elements
b1=matrix_B[0,0]
b2=matrix_B[1,0]
b3=matrix_B[2,0]

In [7]:
# fetching each element in matrix_A
a11=matrix_A[0,0]
a21=matrix_A[1,0]
a31=matrix_A[2,0]
a12=matrix_A[0,1]
a22=matrix_A[1,1]
a32=matrix_A[2,1]
a13=matrix_A[0,2]
a23=matrix_A[1,2]
a33=matrix_A[2,2]

In [8]:
# redefining eah matrices, A1, A2 and A3
print("By substituting column 'i' at the matrix 'Ai', we got:")

By substituting column 'i' at the matrix 'Ai', we got:


In [9]:
matrix_A1 = np.array([[b1, a12, a13],
                      [b2, a22, a23],
                      [b3, a32, a33]])

In [10]:
matrix_A2 = np.array([[a11, b1, a13],
                      [a21, b2, a23],
                      [a31, b3, a33]])

In [11]:
matrix_A3 = np.array([[a11, a12, b1],
                      [a21, a22, b2],
                      [a31, a32, b3]])

In [12]:
print(matrix_A1)

[[39.    1.    1.  ]
 [13.    2.    0.25]
 [45.    1.    2.  ]]


In [13]:
print(matrix_A2)

[[ 2.   39.    1.  ]
 [ 0.3  13.    0.25]
 [ 1.   45.    2.  ]]


In [14]:
print(matrix_A3)

[[ 2.   1.  39. ]
 [ 0.3  2.  13. ]
 [ 1.   1.  45. ]]


In [15]:
det_A1 = linalg.det(matrix_A1)

In [16]:
det_A2 = linalg.det(matrix_A2)

In [17]:
det_A3 = linalg.det(matrix_A3)

In [18]:
# determine variable's values
t = det_A1/det_A

In [19]:
x = det_A2/det_A

In [20]:
n = det_A3/det_A

In [21]:
print('t = ', t)
print('x = ', x)
print('n = ', n)

t =  10.000000000000005
x =  2.9999999999999987
n =  16.00000000000001


In [22]:
print("That's it! Thank you for reading this post o/")

That's it! Thank you for reading this post o/
