Hi, this is PART I that results from the college's subject NUMERIC METHODS while I am coursing COMPUTER ENGENEER at UNINTER (uninter.com).


WELCOME!

Here is the problem to deal with:

### EQUATIONS SYSTEMS - GAUSS JORDAN


A production engineer from an electronics industry analyzes an industrial process in which he considers the assembly time (t), the number of employees (x) and the number of components (n) used in the final product, and reached this system of equations:

The engineer wants to reach an ideal condition for all goals to be achieved, with an estimated accuracy of 0.01 (one hundredth of each variable).

\
  \begin{cases}
      2t + 1x +    1n = 39   & \quad \text{ } t \text{ }\\
    0.3t + 2x + 0.25n = 13   & \quad \text{ } x \text{}\\
       t +  x +    2n = 45  & \quad \text{ } n \text{
       }
  \end{cases}
  
  ####    HOW TO SOLVE THIS PROBLEM USING   GAUSS JORDAN (Matrix Resolution setup):?
  
  The first task is to transform the system into matrices:
  
     [COEFICIENTS]   *   [VAR]  =  [PROBLEM]
  
                [A]  *    [X]   =   [B]       (THIS IS THE equation_0) 
 
\begin{equation}
\frac{
    \begin{array}{r}{}
      \left(   \begin{bmatrix}
      2  & 1   & 1  \quad \\\
     0.3  & 2   & 0.25   \\\
      1   & 1   & 2
      \quad \text{ } \text{}
 \end{bmatrix}  \right)\
      \times \left(   \begin{bmatrix}
      t \\
      x \\
      n \\
      \quad \text{ } \text{}
 \end{bmatrix}    \right)\
     = \left(   \begin{bmatrix}
      39 \\
      13 \\
      45 \\
      \quad \text{ } \text{}
 \end{bmatrix}\right)\
    \end{array}
  }{
    \left(  \begin{array}
    MMATRIX & RESOLUTION & EQUATION
    \quad \text{ } \text{
       }
 \end{array} \right)
  }
\end{equation}
 
     
The solution can be achieved by IDENTITY matrix using this equation:
  
      (IDENTITY)   *   (VAR)  =  (SOLVE)
  
           [I]     *    [X]   =   [S]         (THIS IS THE equation_1)
     
How can we work with IDENTITY matrix? 

We know that:

The matrix itself multiplied by its inverse results in IDENTITY MATRIX, right?

              [A]  *  inv[A]  =   [I]         (THIS IS THE equation_2)
 
So, IN OUR PROBLEM (equation_0):
      
              [A]   *    [X]  =   [B]

THE SOLUTION WOULD BE (equation_1):

              [I]   *    [X]  =   [S] 
             
Substituting I found in the equation (2):

    ([A] * inv[A])  *    [X]  =   [S]  
      
Rearranging:
      
    inv[A]  * ([A]  * [X])    =   [S] 
      
      
But, from equation (1) we have  [A]  *    [X]  =   [B]:
      
      
That implies:

            inv[A]  *   [B]   =   [S] 
       
 So, The solution will be given by multiplying the inverse matrix of [A] with matrix [B]
      
      
  or:
  
             [S]   =  inv[A]  *   [B] 
 
 THIS IS THE REASONING TO BE APPLIED HERE!

  LET'S GET IT ON !!!
 

In [1]:
# Gauss-jordan method
from numpy import matrix, linalg
import numpy as np

In [2]:
# creating the matrices
print("For 'A * X = B' we need to write as 'I * X = S'")

For 'A * X = B' we need to write as 'I * X = S'


In [3]:
matrix_A = np.array([[2.0, 1.0, 1.0],[0.30, 2.0, 0.25],[1.0, 1.0, 2.0]])

In [4]:
matrix_B = np.array([[39.0],[13.0],[45.0]])

In [5]:
print('matrix_A')
print(matrix_A)

matrix_A
[[2.   1.   1.  ]
 [0.3  2.   0.25]
 [1.   1.   2.  ]]


In [6]:
print('matrix_B')
print(matrix_B)

matrix_B
[[39.]
 [13.]
 [45.]]


In [7]:
print("Knowing that 'A * A_inv = I', the solution comes down to 'S = A_inv * B'")

Knowing that 'A * A_inv = I', the solution comes down to 'S = A_inv * B'


In [8]:
# creating the inverse of matrix_A
matrix_A_inv = linalg.inv(matrix_A)
print(matrix_A_inv)

[[ 0.68807339 -0.18348624 -0.32110092]
 [-0.06422018  0.55045872 -0.03669725]
 [-0.31192661 -0.18348624  0.67889908]]


In [9]:
# solution:
matrix_S = np.matmul(matrix_A_inv, matrix_B)
print('matrix_S')
print(matrix_S)

matrix_S
[[10.]
 [ 3.]
 [16.]]


In [10]:
print("That's it! Thanks for reading the post!")

That's it! Thanks for reading the post!
